name: CD Pipeline

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/alchemy

      - name: Empaquetar para distribución
        run: |
          mkdir -p dist
          cp bin/alchemy dist/
          tar czf dist/alchemy-cli.tar.gz -C dist alchemy