name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Verificar estructura
        run: |
          echo "Verificando archivos..."
          ls -la

      - name: Probar comandos básicos
        run: |
          chmod +x bin/alchemy
          ./bin/alchemy help
          ./bin/alchemy version
        
      - name: Validar artefacto antes de la carga
        run: |
          if [ -f ./bin/alchemy ]; then
            echo "Artefacto encontrado. Procediendo con la carga."
          else
            echo "Error: Artefacto no encontrado."
            exit 1
          fi

      - name: Publicar artefacto (opcional)
        uses: actions/upload-artifact@v3
        with:
          name: alchemy-cli
          path: ./bin/alchemy